extends Node

#emitted by dice.gd to transmit itself to main (for HUD)
signal load_dice
signal set_active_dice
signal unset_active_dice
signal power_value
signal active_dice_in_motion
signal active_dice_stationary
signal mouse_enter
signal mouse_enter_upcoming
signal mouse_exit
signal set_arrow_visibility

#Display dice in HUD
signal add_dice_to_upcoming
signal add_dice_to_playable

signal initialise_dice_values
signal move_dice_offscreen
signal update_dice_position

signal close_all_panels

#Score Panel
signal add_dice_to_score
signal update_dice_score
signal update_total_score
signal update_dice_score_label_to_default
signal update_dice_score_label_to_hovered

signal redraw_dice
signal populate_upcoming
signal populate_playable_with_upcoming
signal update_upcoming_sprites
signal update_playable_sprites
signal remove_from_playable_pile

signal add_to_upcoming_panel
signal remove_from_upcoming_panel
signal add_to_playable_panel
signal remove_from_playable_panel

signal set_gamestate
signal update_dice_count
signal update_dice_sprite

signal set_lock_option_visibility
